"""empty message

Revision ID: 21e7bebb41ff
Revises: b0dd03f24103
Create Date: 2018-11-14 15:24:57.248349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e7bebb41ff'
down_revision = 'b0dd03f24103'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('post_text', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'post_text')
    # ### end Alembic commands ###
